EVAL:
    dataset: 'liver' #"liver"             # ('liver') normalement c'est le dossier du dataset 
    arch: 'resnet18'                # ('resnet18')
    method: "paddle" #'simpleshot'                # ('paddle', 'baseline', 'soft_km')
    #n_ways: 6                       # number of different classes represented in the query
    #n_query: 25                     # total number of images in query
    shots: [3, 5, 10, 30, 50, 100, 200, 300, 500, 800, 1000, 1300, 1500, 1800, 2000, 2300, 2500, 2800, 3000]                     # number of shots for which evaluation is performed
    sampling: 'sliding_window' #'squares' #'squares'             # ('same_slice' |  | 'squares') sampling of the query
    overlapping: True      

    number_tasks: "max" #10           # number of tasks to evaluate
    batch_size: 1                   # number of tasks per batch    # laisser à 1, c'est probablement cassé
    #normalisation_couleur: 'no'   # ('no', 'grayscale', 'basic', 'reinhard')  
    #transform_size: 512             # downsampling size we use before extracting features
    #patch_sizes: [3]                # size of the patchs we extract, 0 1 2 3 means 512px, 768px, 1152px, 1728px
    #same_query_size: False          # boolean, if true all query sets have to have exactly n_query examples, if false it can be smaller
    covariance_used: "NONE"       ## GLASSO or NONE # which covariance matrix to use ("NONE", "S_sans_update", "S_updated", "S_full") 
    window_size: 5                  # size of the sliding window if we use "sliding_window" sampling on a full slice 
    s_use_all_train_set: False      # boolean, do we use the whole train set to calculate the covariance matrix
    #trainset_name:  '36I_whole_slide' #'article' #'article' #'63A_whole_slide' #'article'        # the same name that we find in the csv filename 
    #support_hospital: 'kremlin'     # 'kremlin' | 'rouen'
    select_support_nb_elements: False   # False ou a positive integer   # capped simplex
    predire_une_seule_classe: False     # boolean
    #support_dataset_split: 

    prediction: False        ##
    evaluation: True         ##

    evaluation_dir: 'evaluation/fewshots/'
    prediction_dir: 'predictions/fewshots/'

DATA:
    dataset: 'liver'
    root: 'data'
    dataset_path: 'liver'
    batch_size_loader: 256
    enlarge: True
    num_workers: 0
    disable_random_resize: False
    jitter: False


    split_dir: 'data/splits/'

    n_classes: 6
    prefix: '6C'
    support_split_file: '6C_support'  # .csv
    support_split_file_only_augmented: '6C_support_only_augmented'  # .csv
    query_split_file: '6C_query'                ## # .csv


    data_dir_augmented : 'data/augmented_data/'     
    data_dir : 'data/normalized_data/'
    query_data_dir: 'data/normalized_data/'         ##

    features_dir: checkpoints/fewshot/resnet18/extracted_features/
    querysets_dir: checkpoints/fewshot/resnet18/query_sets/

    features_extractor_path: 'checkpoints/fewshot/resnet18/feature_extractor/model_best.ckpt'

    cov_matrix_path: 'checkpoints/fewshot/resnet18/covariance_matrices/'



    # pour tester sur lame complète : sampling à 'sliding_window' 
    # et trainset_name au nom de la lame (comme dans le csv, par exemple 63A_whole_slide)
